# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choise_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogStartAppDbChange(object):
    def setupUi(self, DialogStartAppDbChange):
        DialogStartAppDbChange.setObjectName("DialogStartAppDbChange")
        DialogStartAppDbChange.setWindowModality(QtCore.Qt.NonModal)
        DialogStartAppDbChange.resize(391, 81)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogStartAppDbChange.sizePolicy().hasHeightForWidth())
        DialogStartAppDbChange.setSizePolicy(sizePolicy)
        self.pushButton_choiseFile = QtWidgets.QPushButton(DialogStartAppDbChange)
        self.pushButton_choiseFile.setGeometry(QtCore.QRect(270, 10, 111, 31))
        self.pushButton_choiseFile.setObjectName("pushButton_choiseFile")
        self.lineEdit = QtWidgets.QLineEdit(DialogStartAppDbChange)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_startApp = QtWidgets.QPushButton(DialogStartAppDbChange)
        self.pushButton_startApp.setGeometry(QtCore.QRect(110, 50, 191, 23))
        self.pushButton_startApp.setObjectName("pushButton_startApp")

        self.retranslateUi(DialogStartAppDbChange)
        QtCore.QMetaObject.connectSlotsByName(DialogStartAppDbChange)

    def retranslateUi(self, DialogStartAppDbChange):
        _translate = QtCore.QCoreApplication.translate
        DialogStartAppDbChange.setWindowTitle(_translate("DialogStartAppDbChange", "Выбор файла базы данных \"Малярная мастерская\""))
        self.pushButton_choiseFile.setText(_translate("DialogStartAppDbChange", "Выбрать файл БД"))
        self.pushButton_startApp.setText(_translate("DialogStartAppDbChange", "Запустить сеанс работы"))
