# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_dim_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateDimBackup(object):
    def setupUi(self, DialogCreateDimBackup):
        DialogCreateDimBackup.setObjectName("DialogCreateDimBackup")
        DialogCreateDimBackup.resize(336, 90)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogCreateDimBackup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogCreateDimBackup)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(DialogCreateDimBackup)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(DialogCreateDimBackup)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(DialogCreateDimBackup)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.pushButton_save = QtWidgets.QPushButton(DialogCreateDimBackup)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(DialogCreateDimBackup)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialogCreateDimBackup)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateDimBackup)

    def retranslateUi(self, DialogCreateDimBackup):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateDimBackup.setWindowTitle(_translate("DialogCreateDimBackup", "Создание"))
        self.label.setText(_translate("DialogCreateDimBackup", "Введите наименование:"))
        self.pushButton_save.setText(_translate("DialogCreateDimBackup", "Сохранить"))
        self.pushButton_cancel.setText(_translate("DialogCreateDimBackup", "Отмена"))
