# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dim_elements.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogViewerDimElements(object):
    def setupUi(self, DialogViewerDimElements):
        DialogViewerDimElements.setObjectName("DialogViewerDimElements")
        DialogViewerDimElements.resize(410, 398)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(DialogViewerDimElements)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(DialogViewerDimElements)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.listWidget_dim_elevents = QtWidgets.QListWidget(DialogViewerDimElements)
        self.listWidget_dim_elevents.setObjectName("listWidget_dim_elevents")
        self.verticalLayout.addWidget(self.listWidget_dim_elevents)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialogViewerDimElements)
        QtCore.QMetaObject.connectSlotsByName(DialogViewerDimElements)

    def retranslateUi(self, DialogViewerDimElements):
        _translate = QtCore.QCoreApplication.translate
        DialogViewerDimElements.setWindowTitle(_translate("DialogViewerDimElements", "Просмотр элементов справочника"))
        self.pushButton.setText(_translate("DialogViewerDimElements", "Добавить элементы справочника"))
