# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 488)
        MainWindow.setMaximumSize(QtCore.QSize(1107, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/danon/Pictures/icon/cat/Pop cat closed.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1091, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Date_2 = QtWidgets.QWidget()
        self.tab_Date_2.setObjectName("tab_Date_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_Date_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1081, 451))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_filterDate_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filterDate_2.setObjectName("horizontalLayout_filterDate_2")
        self.comboBox_year_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_year_2.setObjectName("comboBox_year_2")
        self.horizontalLayout_filterDate_2.addWidget(self.comboBox_year_2)
        self.comboBox_month_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_month_2.setObjectName("comboBox_month_2")
        self.horizontalLayout_filterDate_2.addWidget(self.comboBox_month_2)
        self.pushButton_buildReportDate_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_buildReportDate_2.setObjectName("pushButton_buildReportDate_2")
        self.horizontalLayout_filterDate_2.addWidget(self.pushButton_buildReportDate_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_filterDate_2)
        self.horizontalLayout_reprotDate_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reprotDate_2.setObjectName("horizontalLayout_reprotDate_2")
        self.tableView_reprotDate_2 = QtWidgets.QTableView(self.verticalLayoutWidget_4)
        self.tableView_reprotDate_2.setObjectName("tableView_reprotDate_2")
        self.horizontalLayout_reprotDate_2.addWidget(self.tableView_reprotDate_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_reprotDate_2)
        self.tabWidget.addTab(self.tab_Date_2, "")
        self.tab_Emp_2 = QtWidgets.QWidget()
        self.tab_Emp_2.setObjectName("tab_Emp_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_Emp_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 1081, 451))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_filterEmp_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filterEmp_2.setObjectName("horizontalLayout_filterEmp_2")
        self.comboBox_Emp_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.comboBox_Emp_2.setObjectName("comboBox_Emp_2")
        self.horizontalLayout_filterEmp_2.addWidget(self.comboBox_Emp_2)
        self.pushButton_buildReportEmp_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_buildReportEmp_2.setObjectName("pushButton_buildReportEmp_2")
        self.horizontalLayout_filterEmp_2.addWidget(self.pushButton_buildReportEmp_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_filterEmp_2)
        self.horizontalLayout_reportEmp_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reportEmp_2.setObjectName("horizontalLayout_reportEmp_2")
        self.tableView_reprotEmp_2 = QtWidgets.QTableView(self.verticalLayoutWidget_5)
        self.tableView_reprotEmp_2.setObjectName("tableView_reprotEmp_2")
        self.horizontalLayout_reportEmp_2.addWidget(self.tableView_reprotEmp_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_reportEmp_2)
        self.tabWidget.addTab(self.tab_Emp_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Отчет \"Окраска автомобилей\""))
        self.pushButton_buildReportDate_2.setText(_translate("MainWindow", "Построить отчет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Date_2), _translate("MainWindow", "Отчет по дате"))
        self.pushButton_buildReportEmp_2.setText(_translate("MainWindow", "Построить отчет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Emp_2), _translate("MainWindow", "Отчет по работникам"))
